name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  XCODE_VERSION: '16.2'

jobs:
  lint:
    name: Swift Lint
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint --config .swiftlint.yml --reporter github-actions-logging
      continue-on-error: true

  build-test:
    name: Build and Test
    runs-on: macos-15
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Resolve dependencies
      run: |
        xcodebuild -resolvePackageDependencies \
          -project Hex.xcodeproj \
          -scheme Hex \
          -clonedSourcePackagesDirPath SourcePackages
          
    - name: Build
      run: |
        xcodebuild clean build \
          -project Hex.xcodeproj \
          -scheme Hex \
          -configuration ${{ matrix.configuration }} \
          -destination 'platform=macOS,arch=arm64' \
          -clonedSourcePackagesDirPath SourcePackages \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=NO \
          | xcbeautify
          
    - name: Run tests
      run: |
        xcodebuild test \
          -project Hex.xcodeproj \
          -scheme Hex \
          -configuration ${{ matrix.configuration }} \
          -destination 'platform=macOS,arch=arm64' \
          -clonedSourcePackagesDirPath SourcePackages \
          -resultBundlePath TestResults-${{ matrix.configuration }}.xcresult \
          | xcbeautify
          
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results-${{ matrix.configuration }}
        path: TestResults-${{ matrix.configuration }}.xcresult